contact_address = 'crowd.group.mturk@gmail.com'

COGNITIVE_TEST_STROOP = 'stroop'
COGNITIVE_TEST_FLANKER = 'flanker'
COGNITIVE_TEST_TASK_SWITCHING = 'task-switching'
COGNITIVE_TEST_POINTING = 'pointing'
COGNITIVE_TEST_N_BACK = 'n-back'

CROWD_TASK_SENTIMENT = 'sentiment'
CROWD_TASK_TRANSCRIPTION = 'transcription'
CROWD_TASK_PROOFREADING = 'proofreading'
CROWD_TASK_CLASSIFICATION = 'classification'
CROWD_TASK_COUNTING = 'counting'

STUDY_CONDITION_BASELINE = '0'
STUDY_CONDITION_COGNITIVE_ASSIGN = '1'
STUDY_CONDITION_COGNITIVE_RECOMMEND = '2'
STUDY_CONDITION_QASCA = '3'
STUDY_CONDITION_CROWD_DQS = '4'

NUMBER_OF_QUESTIONS_PER_ASSIGNMENT = 3
MAX_NUMBER_OF_COGNITIVE_TESTS_PER_ASSIGNMENT = 2

CROWD_TASK_LABELS = {
    CROWD_TASK_CLASSIFICATION: '1',
    CROWD_TASK_COUNTING: '2',
    CROWD_TASK_PROOFREADING: '3',
    CROWD_TASK_SENTIMENT: '4',
    CROWD_TASK_TRANSCRIPTION: '5'
}

CROWD_TASK_THRESHOLDS = {
    CROWD_TASK_CLASSIFICATION: 0.677,
    CROWD_TASK_COUNTING: 0.637,
    CROWD_TASK_PROOFREADING: 0.427,
    CROWD_TASK_SENTIMENT: 0.839,
    CROWD_TASK_TRANSCRIPTION: 0.772
}

CROWD_TASKS = [CROWD_TASK_CLASSIFICATION, CROWD_TASK_COUNTING, CROWD_TASK_PROOFREADING,
               CROWD_TASK_SENTIMENT, CROWD_TASK_TRANSCRIPTION]

COGNITIVE_TESTS = [COGNITIVE_TEST_STROOP, COGNITIVE_TEST_FLANKER, COGNITIVE_TEST_N_BACK,
                   COGNITIVE_TEST_TASK_SWITCHING, COGNITIVE_TEST_POINTING]
