# Generated by Django 2.1.3 on 2018-11-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0002_auto_20181109_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='begin_exp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='begin_hit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_hit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='qualification',
            field=models.IntegerField(default=0),
        ),
    ]
