# Generated by Django 2.1.3 on 2018-12-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0003_auto_20181109_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questions_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('total_assignments', models.IntegerField()),
                ('available_assignments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('task_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Working'), (2, 'Completed'), (3, 'Abandoned')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workertasks.Task'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('questions_id', 'task_id')},
        ),
    ]
