# Generated by Django 2.1.3 on 2018-12-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0004_auto_20181212_0405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questions_id',
            new_name='question_id',
        ),
        migrations.AlterField(
            model_name='question',
            name='available_assignments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_id', 'task_id')},
        ),
    ]
