# Generated by Django 2.1.3 on 2019-03-08 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0005_auto_20181212_0548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('condition_name', models.CharField(max_length=64)),
                ('condition_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Working'), (2, 'Completed'), (3, 'Abandoned')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='condition_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='workertasks.Condition'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='condition_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workertasks.Condition'),
            preserve_default=False,
        ),
    ]
