# Generated by Django 2.1.3 on 2019-03-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0007_auto_20190311_0431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='worker_id',
            new_name='worker_uid',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='task_id',
            new_name='task_uid',
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_id', 'task_uid')},
        ),
        migrations.AlterUniqueTogether(
            name='worker',
            unique_together={('worker_id', 'condition_id')},
        ),
    ]
