# Generated by Django 2.1.3 on 2019-03-12 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0008_auto_20190311_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
