# Generated by Django 2.1.3 on 2019-03-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0010_auto_20190320_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
