# Generated by Django 2.1.3 on 2019-04-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0011_assignment_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set(),
        ),
    ]
