# Generated by Django 2.1.3 on 2019-04-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0012_auto_20190424_0542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_id', 'task_uid')},
        ),
    ]
