# Generated by Django 2.1.3 on 2019-04-30 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0013_auto_20190424_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCompletion',
            fields=[
                ('question_completion_uid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('question_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'Working'), (2, 'Completed'), (3, 'Abandoned')], default=0)),
                ('answer', models.TextField(blank=True, null=True)),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workertasks.Condition')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workertasks.Question')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workertasks.Worker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='questioncompletion',
            unique_together={('question', 'worker', 'condition')},
        ),
    ]
