# Generated by Django 2.1.3 on 2019-04-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0014_auto_20190430_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncompletion',
            name='task',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, to='workertasks.Task'),
            preserve_default=False,
        ),
    ]
