# Generated by Django 2.1.3 on 2019-05-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0015_questioncompletion_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number_of_questions',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
