# Generated by Django 2.1.3 on 2019-06-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0018_assignment_task_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='distribution',
            field=models.CharField(default='', max_length=250),
        ),
    ]
