# Generated by Django 2.1.3 on 2019-06-12 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0019_question_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='quality',
            field=models.FloatField(default=1),
        ),
    ]
