# Generated by Django 2.1.3 on 2019-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workertasks', '0020_worker_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='quality',
            field=models.FloatField(default=0.7),
        ),
    ]
